### ISSUE TITLE
Changing filepath in cookie to other directories

### ISSUE THREAD

**Issue by ryananeff** [ehhop/ehhapp-formulary#13]
The formulary code allows all filenames and paths to be passed via the cookie, not just allowed filenames or random strings that correspond to filenames. These files are then processed via json.loads(), yada yada yada, bad things can happen if abused.

https://github.com/ehhop/ehhapp-formulary/blob/2056986ba85b03097570b3e04f736d2300a0d313/__init__.py#L110-L142

**Comment by daviszhou** [comment]
Thanks for catching this!

**Comment by ryananeff** [comment]
@briancho94 @dchary wanted to share this with you as a learning opportunity when building out this app
